### ISSUE TITLE
running npm-sort gives errors

### ISSUE THREAD

**Issue by Melindrea** [kilianc/npm-sort#1]
I installed npm-sort globally as per the installation, but when running it in my project, I get the following:

```
> Sorting dependencies...

/home/marie/.nvm/v0.10.17/lib/node_modules/npm-sort/index.js:25
var keys = Object.keys(obj).sort(function (a, b) {
                ^
TypeError: Object.keys called on non-object
at Function.keys (native)
at sortObject (/home/marie/.nvm/v0.10.17/lib/node_modules/npm sort/index.js:25:21)
at sortDeps (/home/marie/.nvm/v0.10.17/lib/node_modules/npm-sort/index.js:10:22)
at Object.<anonymous> (/home/marie/.nvm/v0.10.17/lib/node_modules/npm-sort/index.js:37:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
```

[Package.json](https://github.com/Melindrea/security-application/blob/master/package.json)

My system is Ubuntu 64-bit, Nodejs v0.10.17.

**Comment by kilianc** [comment]
Looking into it.

**Comment by kilianc** [comment]
@Melindrea `npm install npm-sort -g` again.

**Comment by Melindrea** [comment]
Still getting that error on v0.0.2 Though, could it affect things that I have no dependencies, only devDependencies? (It's a PHP project using Grunt as a taskrunner)

**Comment by kilianc** [comment]
@Melindrea I just bumped to v0.0.3 update your bin please

**Comment by Melindrea** [comment]
Alright! Now it works, good job!
